### ISSUE TITLE
Make service do Spacewalk vault client integration tests on Pendulum

### ISSUE THREAD

**Issue by annatekl** [pendulum-chain/spacewalk-testing-service#10]
This ticket is about extending the current configuration of tested vault clients to also include the Pendulum vaults. 
So we just need to extend the configuration file with those details once known.

You can find the information about the Pendulum vaults in [this](https://www.notion.so/satoshipay/Spacewalk-Vault-Client-Information-0f9e02b91c54422dbc42a5e4172781ff) Notion page. Edit [this](https://github.com/pendulum-chain/spacewalk-testing-service/blob/main/config.json) config file.

**Comment by annatekl** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/spacewalk-testing-service/10?planning-poker) with Zenhub @b-yap @bogdanS98 @ebma @gianfra-t @TorstenStueber

**Comment by ebma** [comment]
@annatekl I changed the description. For this ticket to work, we first need to know the accounts of the vaults on Pendulum. Can you please link to that other ticket where those accounts are created?

**Comment by prayagd** [comment]
@ebma is this ticket required before root transaction or after it?

**Comment by ebma** [comment]
It's required after we registered the vaults on Pendulum ie after https://github.com/pendulum-chain/tasks/issues/239

**Comment by prayagd** [comment]
@annatekl above message FYI
