### ISSUE TITLE
Try reconnecting API for bad signature errors

### ISSUE THREAD

**Issue by ebma** [pendulum-chain/spacewalk-testing-service#11]
Follow-up for https://github.com/pendulum-chain/pendulum/issues/411

## Context
We saw that the service might get stuck with
```
2024-02-13 23:32:06        RPC-CORE: submitAndWatchExtrinsic(extrinsic: Extrinsic): ExtrinsicStatus:: 1010: Invalid Transaction: Transaction has a bad signature
RpcError: 1010: Invalid Transaction: Transaction has a bad signature
    at file:///app/spacewalk-testing-service/dist/vault_service/vault.js:50:24
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///app/spacewalk-testing-service/dist/vault_service/vault.js:18:13 {
  extrinsicCalled: 'Issue Request',
  sender: '6kmmmu4nTuELg5xXqLvfK9TzMsUgmqZEX4iGpMXmQWm71271'
}
```

when using a cached `api` object after a runtime upgrade was executed on a network.

## TODO

We should keep the caching logic but add handling so that once the error is encountered, the `api` object is re-instantiated (just creating a new `api` connecting to the same network should be enough).

**Comment by ebma** [comment]
@pendulum-chain/product this ticket solves a problem where our service can get stuck after a runtime upgrade happened.

**Comment by prayagd** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/spacewalk-testing-service/11?planning-poker) with Zenhub @b-yap @bogdanS98 @ebma @gianfra-t @TorstenStueber

**Comment by TorstenStueber** [comment]
@prayagd @ebma Can we move this to Ready?

**Comment by gianfra-t** [comment]
I think the fix would be similar as [this](https://github.com/pendulum-chain/faucet/pull/4) one here right?

**Comment by ebma** [comment]
Yes I think the implementation would be similar 👍
