### ISSUE TITLE
Service gets stuck with tests running infinitely and does not start new tests.

### ISSUE THREAD

**Issue by gianfra-t** [pendulum-chain/spacewalk-testing-service#14]
### Error Description
The test service shows in the logs for some testing configurations `Test already running for vault ..... at stage request_issue_completed` even after well passed the maximum delay time of the vault to complete. 
These tests, successful or not, should have been removed from the `testStages` [list](https://github.com/pendulum-chain/spacewalk-testing-service/blob/main/src/test/test.ts#L38) and should have allowed others to start.

The error `StellarAccountError: Unknown stellar account error` was seen just before this behavior started.

### Context
As soon as any test instance starts, the service will push this instance into a state variable `testStages`. If for some reason the scheduler attempts to start a test with the same configuration while the previous one is still ongoing, it will just [ignore](https://github.com/pendulum-chain/spacewalk-testing-service/blob/main/src/test/test.ts#L54) the start of the new one.
After some maximum time the redeem/issue request will time out, returning an error which will stop the test and [remove](https://github.com/pendulum-chain/spacewalk-testing-service/blob/main/src/test/test.ts#L82) it from the state.

### Possible causes and fixes
Somehow the `StellarAccountError: Unknown stellar account error` error may have ended the test but withouth it going through the removal process, or it could have created a never ending process that is currently not checked by any timer.

We could try to replicate this error (which probably occurred [here](https://github.com/pendulum-chain/spacewalk-testing-service/blob/main/src/test/test.ts#L129)), and to fix it we should ensure that it produces an error immediately which triggers the end of the test.

**Comment by prayagd** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/spacewalk-testing-service/14?planning-poker) with Zenhub @b-yap @bogdanS98 @ebma @gianfra-t @TorstenStueber
